### ISSUE TITLE
towns of a country

### ISSUE THREAD

**Issue by dragonjon** [agh1/com.aghstrategies.uscounties#1]
Is it possible to do the same with the towns of a country?
Thanks

**Comment by agh1** [comment]
It could be done.  The important thing is that the county features are already built into CiviCRM; this just populates the county names into the database under the appropriate states.  If you're loading towns, you'll need to use word replacements to rename it.

You also may find it redundant to have the town recorded in the city field as well as the county field.

The real thing is that some countries have their states/provinces divided into subdivisions like counties or parishes, but others don't.  If you're using something that doesn't match the pattern of counties, you can certainly do it, but it won't necessarily work as well as you might imagine.
