### ISSUE TITLE
Mark 4.7-compatible

### ISSUE THREAD

**Issue by MegaphoneJon** [agh1/com.aghstrategies.uscounties#2]
I see you marked it, then unmarked it.  I successfully tested it!  I could submit a PR, but that seems silly.

**Comment by MegaphoneJon** [comment]
I downloaded the zip from master, and info.xml was still marked as 4.7-compatible there?  I took the liberty of uploading that info.xml to c.o so that this appears in-app for 4.7 users, hope I'm not stepping on your toes!

**Comment by agh1** [comment]
Awesome, thanks so much @PalanteJon!  I must have intended to and then got interrupted.
