### ISSUE TITLE
Broomfield County missing for Colorado

### ISSUE THREAD

**Issue by andyburnsco** [agh1/com.aghstrategies.uscounties#3]
Broomfield County is missing for Colorado. It didn't appear to be a new county so wondering how we can implement a fix if we already are using the county loader?

**Comment by andyburnsco** [comment]
Checking back...

**Comment by lordofthegithub** [comment]
Two ways to do it;

A. Extension Method:
A1. Insert the "Broomfield" as a value in the Array for the state "Colorado" in the file
A2. disable the Extension
A3. enable the Extension

Hopefully that will fix it.

Much safer alternative is below :

2. Direct SQL Insert

INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL, 'Broomfield', NULL, '1006');

Hope this helps.

**Comment by andyburnsco** [comment]
We did #2 just before you sent this. It worked.
