### ISSUE TITLE
County list showing all counties in the USA, not sorting by state

### ISSUE THREAD

**Issue by wrmark** [agh1/com.aghstrategies.uscounties#7]
![Screenshot 2021-09-08_county-list](https://user-images.githubusercontent.com/29133951/132527803-d6d0b906-3c48-4523-b823-2596aac9ab78.png)

**Comment by andyburnsco** [comment]
Make sure the state and county fields are of the same location type.

**Comment by wrmark** [comment]
Perfect! That did it. Thanks!
